declare module '*.png'
declare module '*.ogg'
declare module '*.json'
declare module '*.wav'
declare module '*.js'
declare module '*.ts'
declare module 'heartbeats'
declare module '@pixi-essentials/object-pool'
